# Generated by Django 2.2.15 on 2020-08-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_max_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='templates',
            field=models.TextField(blank=True, help_text='Optional file templates for this task, encoded in JSON', null=True),
        ),
    ]
